#ifndef TEAMPLANNER_CONSTANTDEF_HPP
#define TEAMPLANNER_CONSTANTDEF_HPP

enum RandomType{
    TEAMPLANNER_GAUSSIAN = 0,
    TEAMPLANNER_READ = 1
};

enum ModelType{
    TEAMPLANNER_DET = 0,
    TEAMPLANNER_SPR = 1,
    TEAMPLANNER_CCP = 2,
    TEAMPLANNER_SPRITER = 3,
    TEAMPLANNER_CCPCONE = 4,
    TEAMPLANNER_CCPITER = 5,
    TEAMPLANNER_TASKLIN = 6,
    TEAMPLANNER_TASKLSHAPED = 7,
    TEAMPLANNER_TASKNON = 8,
    TEAMPLANNER_CONDET = 9,
    TEAMPLANNER_CONTASKLIN = 10,
    TEAMPLANNER_CONTASKLSHAPED = 11
};

#endif //TEAMPLANNER_CONSTANTDEF_HPP